# Generated by Django 4.0.5 on 2022-07-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='comments',
            field=models.CharField(default='', max_length=140),
        ),
    ]
