# Generated by Django 4.0.5 on 2022-07-24 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuals',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
    ]
