# Generated by Django 4.0.5 on 2022-07-25 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_remove_actuals_user_remove_budget_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_feild',
            field=models.CharField(max_length=100),
        ),
    ]
